"""empty message

Revision ID: 05fd4c5b313d
Revises: 
Create Date: 2024-02-14 16:01:55.866034

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05fd4c5b313d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
