#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
	celery -A backend.main.celery inspect ping
}

until worker_ready; do
	>&2 echo 'Celery workers unavailable'
	sleep 1
done
>&2 echo 'Celery workers are available'

celery flower \
	--app=backend.main.celery \
	--broker="${CELERY_BROKER_URL}"
